from enum import Enum, unique

@unique
class TokenType(Enum):
	STRING = 1,
	IDENTIFIER = 2,
	NUMBER = 3,
	LINE_COMMENT = 4,
	BLOCK_COMMENT = 5,
	SEMICOLON = 6,
	COMMA = 7,
	OPEN_PARENTHESES = 8,
	CLOSE_PARENTHESES = 9,
	OPEN_BRACKETS = 10,
	CLOSE_BRACKETS = 11,
	OPEN_CURLY_BRACES = 12,
	CLOSE_CURLY_BRACES = 13,
	DOT = 14,
	STRING_ERROR = 15,
	BLOCK_COMMENT_ERROR = 16,
	NUMBER_ERROR = 17,
	ARITHMETIC_ADDER = 18,
	ARITHMETIC_INCREMENT = 19,
	ARITHMETIC_DIVISOR = 20,
	ARITHMETIC_MULT = 21,
	ARITHMETIC_SUBTRACTOR = 22,
	ARITHMETIC_DECREMENT = 23,
	DIFFERENT = 24,
	EQUAL = 25,
	LESSER_THAN = 26,
	LESSER_EQUAL_THAN = 27,
	GREATER_THAN = 28,
	GREATER_EQUAL_THAN = 29,
	ASSINGMENT = 30,
	NOT = 31,
	AND = 32,
	OR = 33,
	INVALID_CHARACTER = 34

keywords = {
	"var": "VAR",
	"const": "CONST",
	"struct": "STRUCT",
	"extends": "EXTENDS",
	"procedure": "PROCEDURE",
	"function": "FUNCTION",
	"start": "START",
	"return": "RETURN",
	"if": "IF",
	"else": "ELSE",
	"then": "THEN",
	"while": "WHILE",
	"read": "READ",
	"print": "PRINT",
	"int": "INT",
	"real": "REAL",
	"boolean": "BOOLEAN",
	"string": "STRING",
	"true": "TRUE",
	"false": "FALSE",
}